#!/usr/bin/env python3
"""
Idempotent script to build and publish the card-capture CUDA Docker image,
then register it as the vast_template_id in card_capture_config.json.

Usage:
    python3 scripts/setup_cuda_template.py --docker-user jpglick
    python3 scripts/setup_cuda_template.py --docker-user jpglick --verify
    python3 scripts/setup_cuda_template.py --docker-user jpglick --tag v2

Prerequisites:
    GitHub PAT with scopes: write:packages  read:packages  delete:packages
    Create at:  github.com → Settings → Developer settings → Personal access tokens (classic)
    The script will prompt for the token on first run and log in to ghcr.io for you.

What it does:
  1. Writes Dockerfile.cuda to the repo root (if different from what's there).
  2. Builds the image — idempotent via Docker layer cache.
  3. Compares local image digest against Docker Hub; skips push if identical.
  4. Updates card_capture_config.json with the full image name as vast_template_id.
  5. With --verify: provisions a temporary vast.ai instance, runs a smoke test,
     then immediately destroys it. Requires VAST_API_KEY in the environment.

The resulting image is ~12-15 GB and includes:
  - PyTorch 2.3 + CUDA 12.1
  - decord (NVDEC), ultralytics, kornia, fastapi, httpx
  - Pre-cached YOLO OBB model weights
  - Pre-cached DINOv2 vits14 weights
  - The card-capture repo at the time of build (git pull on each instance boot)

On each boot the vast.ai worker runs:
  git pull && pip install -e '.[app]' -q && uvicorn app.vastai_worker:app --host 0.0.0.0 --port 8765
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
CONFIG_PATH = REPO_ROOT / "card_capture_config.json"

# ── Dockerfile content ────────────────────────────────────────────────────────

DOCKERFILE = """\
# card-capture CUDA base image
# Generated by scripts/setup_cuda_template.py — edit that script to change this.
FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-devel

ENV DEBIAN_FRONTEND=noninteractive

# System packages needed by OpenCV, decord, and ffmpeg
RUN apt-get update -q && apt-get install -y -q --no-install-recommends \\
        git ffmpeg libsm6 libxext6 libgl1 \\
    && rm -rf /var/lib/apt/lists/*

# Heavy Python deps (baked in so boot time is fast)
# decord: NVDEC GPU-accelerated video decode
# ultralytics: YOLOv8 (also pulls torch/torchvision, which are already present)
# kornia: GPU image warping for the refine step
RUN pip install --no-cache-dir \\
        "decord>=0.6.0" \\
        "ultralytics>=8.1.0" \\
        "kornia>=0.7.2" \\
        "httpx>=0.27.0" \\
        "fastapi>=0.110.0" \\
        "uvicorn[standard]>=0.29.0" \\
        "python-multipart>=0.0.9"

# Clone the repo and install the package (app layer only — no model weights yet)
RUN git clone https://github.com/jpglick/card-capture.git /workspace/card-capture
WORKDIR /workspace/card-capture
RUN pip install --no-cache-dir -e ".[model,app]"

# ── Pre-cache model weights (these are large; baking them avoids per-boot downloads) ──

# YOLOv8-OBB corner detector (~160 MB)
RUN python - <<'PYEOF'
try:
    from card_capture.detectors import CardcaptorUltralyticsDetector
    CardcaptorUltralyticsDetector(device="cuda")._load_model()
    print("[template] YOLO model cached ok")
except Exception as e:
    print(f"[template] WARNING: YOLO cache failed (no GPU during build): {e}")
PYEOF

# MobileNetV3 presence classifier (~6 MB, already in models/ dir)
# No extra download needed — it ships with the repo.

# DINOv2 vits14 (~330 MB via torch.hub)
RUN python - <<'PYEOF'
try:
    import torch
    torch.hub.load("facebookresearch/dinov2", "dinov2_vits14", pretrained=True)
    print("[template] DINOv2 cached ok")
except Exception as e:
    print(f"[template] WARNING: DINOv2 cache failed (no GPU during build): {e}")
PYEOF

# ── Boot entrypoint (overridden by vastai_worker onstart script) ──────────────
# The actual boot command written by VastAIClient.provision() is:
#   cd /workspace/card-capture && git pull origin main -q && \\
#   pip install -e '.[app]' -q && \\
#   uvicorn app.vastai_worker:app --host 0.0.0.0 --port 8765
# This CMD is only used if running the image outside vast.ai.
CMD ["uvicorn", "app.vastai_worker:app", "--host", "0.0.0.0", "--port", "8765"]
"""

# ── Helpers ───────────────────────────────────────────────────────────────────

def run(cmd: list[str], check: bool = True, capture: bool = False) -> subprocess.CompletedProcess:
    print(f"  $ {' '.join(cmd)}")
    return subprocess.run(
        cmd, check=check,
        capture_output=capture,
        text=capture,
    )


REGISTRY = "ghcr.io"


def ensure_ghcr_login(github_user: str) -> None:
    """Check ghcr.io auth; prompt for GitHub PAT if not authenticated."""
    config_path = Path.home() / ".docker" / "config.json"
    cfg: dict = {}
    if config_path.exists():
        try:
            cfg = json.loads(config_path.read_text())
        except Exception:
            pass
    auths = cfg.get("auths", {})
    if REGISTRY in auths and auths[REGISTRY].get("auth"):
        return  # Already authenticated — token present in config

    # Not logged in — prompt for GitHub PAT
    print(f"\n⚠️  Not logged in to {REGISTRY} as {github_user!r}.")
    print("  GitHub Container Registry uses a Personal Access Token (classic).")
    print("  Required scopes:  write:packages  read:packages  delete:packages")
    print("  Create one at:  github.com → Settings → Developer settings → Personal access tokens\n")
    token = input("  Paste your GitHub PAT here (leave blank to abort): ").strip()
    if not token:
        sys.exit("Aborted. Create a PAT at github.com → Settings → Developer settings.")

    # Write auth directly to ~/.docker/config.json — avoids macOS Keychain which
    # blocks 'docker login' from the terminal with "User interaction is not allowed".
    import base64
    encoded = base64.b64encode(f"{github_user}:{token}".encode()).decode()
    cfg.setdefault("auths", {})[REGISTRY] = {"auth": encoded}
    # Also strip credsStore if present — Docker Desktop puts this back sometimes
    cfg.pop("credsStore", None)
    config_path.write_text(json.dumps(cfg, indent=2))
    print(f"  ✅ Credentials written directly to {config_path} (bypasses macOS Keychain)")


def image_digest_local(image: str) -> str | None:
    """Return the local image digest, or None if not present."""
    result = subprocess.run(
        ["docker", "inspect", "--format", "{{.Id}}", image],
        capture_output=True, text=True,
    )
    return result.stdout.strip() if result.returncode == 0 else None


def image_digest_remote(image: str) -> str | None:
    """Return the remote Docker Hub digest, or None if not pushed yet."""
    result = subprocess.run(
        ["docker", "manifest", "inspect", image],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        return None
    try:
        data = json.loads(result.stdout)
        return data.get("config", {}).get("digest")
    except Exception:
        return None


def update_config(image_name: str) -> None:
    """Write image_name as vast_template_id in card_capture_config.json."""
    cfg: dict = {}
    if CONFIG_PATH.exists():
        try:
            cfg = json.loads(CONFIG_PATH.read_text())
        except Exception:
            pass
    cfg["vast_template_id"] = image_name
    CONFIG_PATH.write_text(json.dumps(cfg, indent=2))
    print(f"\n✅ Updated card_capture_config.json → vast_template_id = {image_name!r}")


def verify_with_vastai(image_name: str, api_key: str) -> None:
    """Spin up a cheap vast.ai instance, smoke-test it, destroy it."""
    import os as _os
    env = {**_os.environ, "VAST_API_KEY": api_key}

    print("\n── Verify: searching for a cheap offer ──")
    result = subprocess.run(
        ["vastai", "search", "offers", "gpu_name=RTX_3080 num_gpus=1 reliability>0.90", "--raw"],
        capture_output=True, text=True, env=env, check=True,
    )
    offers = json.loads(result.stdout)
    if not offers:
        print("WARNING: no offers found for smoke-test — skipping verify")
        return
    offers.sort(key=lambda o: o.get("dph_total", 999))
    offer_id = offers[0]["id"]
    print(f"  Using offer {offer_id} (${offers[0].get('dph_total', '?'):.3f}/hr)")

    # Provision
    onstart = (
        "cd /workspace/card-capture && git pull origin main -q && "
        "pip install -e '.[app]' -q && "
        "uvicorn app.vastai_worker:app --host 0.0.0.0 --port 8765 &"
    )
    create_result = subprocess.run(
        ["vastai", "create", "instance", str(offer_id),
         "--image", image_name, "--onstart", onstart, "--ports", "8765", "--raw"],
        capture_output=True, text=True, env=env, check=True,
    )
    instance_id = json.loads(create_result.stdout).get("new_contract")
    print(f"  Instance {instance_id} provisioned — waiting for IP…")

    # Wait for IP
    ip = None
    for _ in range(24):
        time.sleep(5)
        show = subprocess.run(
            ["vastai", "show", "instances", "--raw"],
            capture_output=True, text=True, env=env,
        )
        for inst in json.loads(show.stdout or "[]"):
            if inst.get("id") == instance_id and inst.get("public_ipaddr"):
                ip = inst["public_ipaddr"]
                break
        if ip:
            break

    if not ip:
        print("WARNING: instance never got an IP — destroying and skipping smoke test")
    else:
        print(f"  IP: {ip} — waiting for worker health check…")
        import urllib.request
        healthy = False
        for _ in range(36):
            time.sleep(5)
            try:
                with urllib.request.urlopen(f"http://{ip}:8765/health", timeout=4) as r:
                    if r.status == 200:
                        healthy = True
                        break
            except Exception:
                pass
        if healthy:
            print("  ✅ Worker health check passed")
        else:
            print("  ⚠️  Worker did not become healthy within 3 minutes")

    # Always destroy
    print(f"  Destroying instance {instance_id}…")
    subprocess.run(
        ["vastai", "destroy", "instance", str(instance_id), "--raw"],
        env=env,
    )
    print("  Instance destroyed.")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--docker-user", required=True, help="GitHub username for ghcr.io (e.g. jpglick)")
    parser.add_argument("--tag", default="latest", help="Image tag (default: latest)")
    parser.add_argument("--verify", action="store_true", help="Spin up a test instance after push to verify the image")
    parser.add_argument("--force-push", action="store_true", help="Push even if remote digest matches local")
    args = parser.parse_args()

    image_name = f"{REGISTRY}/{args.docker_user}/card-capture-cuda:{args.tag}"
    dockerfile_path = REPO_ROOT / "Dockerfile.cuda"

    print(f"\n{'─'*60}")
    print(f"  card-capture CUDA template setup")
    print(f"  Registry: {REGISTRY}")
    print(f"  Image:    {image_name}")
    print(f"{'─'*60}\n")

    # ── Step 1: Write Dockerfile ──────────────────────────────────────────────
    if not dockerfile_path.exists() or dockerfile_path.read_text() != DOCKERFILE:
        print("── Step 1: Writing Dockerfile.cuda ──")
        dockerfile_path.write_text(DOCKERFILE)
        print("  Written.\n")
    else:
        print("── Step 1: Dockerfile.cuda unchanged — skipping write ──\n")

    # ── Step 2: Build ─────────────────────────────────────────────────────────
    print("── Step 2: Building Docker image (layer cache makes this fast on re-runs) ──")
    run(["docker", "build", "-f", str(dockerfile_path), "-t", image_name, str(REPO_ROOT)])
    print()

    # ── Step 3: Push (skip if digest matches) ────────────────────────────────
    print("── Step 3: Comparing digests ──")
    local_digest = image_digest_local(image_name)
    remote_digest = image_digest_remote(image_name)
    print(f"  local:  {local_digest or '(not built yet)'}")
    print(f"  remote: {remote_digest or '(not pushed yet)'}")

    if not args.force_push and local_digest and remote_digest and local_digest == remote_digest:
        print("  Digests match — skipping push (use --force-push to override)\n")
    else:
        print("── Step 3b: Checking ghcr.io auth ──")
        ensure_ghcr_login(args.docker_user)
        print("── Pushing to Docker Hub ──")
        try:
            run(["docker", "push", image_name])
        except subprocess.CalledProcessError as exc:
            print(f"\n❌ Push failed (exit code {exc.returncode}).")
            print("   Common fixes:")
            print(f"   1. Re-authenticate:  echo YOUR_PAT | docker login {REGISTRY} --username {args.docker_user} --password-stdin")
            print("   2. Ensure your PAT has write:packages scope")
            print("   3. The package will be created automatically on first push (no manual repo creation needed)")
            print("   4. Re-run this script.")
            sys.exit(1)
        print()

    # ── Step 4: Update config ─────────────────────────────────────────────────
    print("── Step 4: Updating card_capture_config.json ──")
    update_config(image_name)

    # ── Step 5: Verify (optional) ─────────────────────────────────────────────
    if args.verify:
        api_key = os.environ.get("VAST_API_KEY", "")
        if not api_key:
            print("\n⚠️  --verify requires VAST_API_KEY env var — skipping")
        else:
            print("\n── Step 5: Verifying on a real vast.ai instance ──")
            verify_with_vastai(image_name, api_key)

    print(f"\n🎉 Done. Use this image in vast.ai runs:")
    print(f"   vast_template_id = {image_name!r}")
    print(f"\n   To re-run (idempotent): python3 scripts/setup_cuda_template.py --docker-user {args.docker_user} --tag {args.tag}")


if __name__ == "__main__":
    main()
